# SignPath configuration for Comet Browser
# Free code signing provided by SignPath Foundation

version: 1.0

artifacts:
  - name: Comet Browser Windows Installer
    description: Windows NSIS installer for Comet Browser
    type: nsis-installer
    
    file-metadata-restrictions:
      product-name: Comet Browser
      product-version: ${VERSION}
      
    signing-configuration:
      kind: authenticode
      
  - name: Comet Browser Executable  
    description: Main Comet Browser executable
    type: pe-file
    
    file-metadata-restrictions:
      product-name: Comet Browser
      product-version: ${VERSION}
      
    signing-configuration:
      kind: authenticode
